### ISSUE TITLE
add your resume

### ISSUE THREAD

**Issue by Vaishnavi584** [GOOGLYYBEAR/Resume-building#1]
vs code

**Comment by Vaishnavi584** [comment]
[A1_46 Vaishnavi Mishra.pdf](https://github.com/GOOGLYYBEAR/Resume-building/files/14892971/A1_46.Vaishnavi.Mishra.pdf)

**Comment by Vaishnavi584** [comment]
done

**Comment by Vinitkhapekar** [comment]
[Vinit_git.pdf](https://github.com/GOOGLYYBEAR/Resume-building/files/14893053/Vinit_git.pdf)

**Comment by Vinitkhapekar** [comment]
Done

**Comment by Saloniraut** [comment]
[RESUME_SALONIRAUT.pdf](https://github.com/GOOGLYYBEAR/Resume-building/files/14893061/RESUME_SALONIRAUT.pdf)

**Comment by Saloniraut** [comment]
done
